[tool.poetry]
name = "icm-shruti-analysis"
version = "0.1.0"
description = ""
authors = ["neerajaabhyankar <neeraja93.a@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
jupyter = "^1.0.0"
plotly = "^5.3.1"
numpy = "1.19"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
